# Zenith builds using the original Corne keymap and vendor hardware definitions.
include:
  - board: seeeduino_xiao_ble
    shield: zenith_left
    artifact-name: zenith_left_corne
  - board: seeeduino_xiao_ble
    shield: zenith_right
    artifact-name: zenith_right_corne
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: zenith_settings_reset
